### ISSUE TITLE
Labeled data is occasionally not being saved

### ISSUE THREAD

**Issue by rojasgabriel** [jcouto/labdata-tools#8]
Labeled data is not being saved properly sometimes. Need to investigate this further. Waiting on error log from @uclaletizia.

**Comment by lsye00** [comment]
Here are some bugs occur without manifesting in an error log:

1. Many user buttons are missing from the GUI that would originally allow the user to select and toggle the different body parts via a drop-down menu. Labeling settings (loop, lock labels etc.) are also unavailable to the user.
2. It is possible for the user to add duplicate annotations of the same body part label on the same frame. (See below.)
3. Labeled data points are not saving and a CollectedData.csv file is not created after annotation in the 'labeled-data' folder.

![image](https://github.com/user-attachments/assets/1254abb4-fbab-4388-ae68-ea13b17f13f1)

Command will execute without resulting in any errors, however.

**Comment by jcouto** [comment]
Seems like a napari-deeplabcut issue. What version are you using and what version of the deeplabcut napari plugin?

**Comment by rojasgabriel** [comment]
Now works after changing `napari` version to `0.4.17`!
